#Fri Apr 25 21:20:39 MSK 2025
buildDir=build
build_dir=build
javaVersion=8
mainClass=A
musicPath=music
org.gradle.jvmargs=-Xmx12g -XX\:MaxMetaspaceSize\=512m -XX\:+UseParallelGC -Dfile.encoding\=UTF-8 -Dkotlin.daemon.jvm.options\=-Xmx2g,-XX\:MaxMetaspaceSize\=1536m,-XX\:+UseParallelGC
pathToXML=src/main/resources/META-INF
resourceDir=src/main/resources
sourceDir=src/main/java
source_dir=src/main/java
classes_dir=build/classes
targetDir=target
testDir=src/test/java
version=1.0
